set(HAS_CUDA_CUB 0)
if(CMAKE_CUDA_COMPILER)
    find_package(CUDAToolkit)
    if(CUDAToolkit_FOUND)
        set(HAS_CUDA_CUB 1)
    endif()
endif()

set(HAS_HIP_CUB 0)
if(CMAKE_HIP_COMPILER)
    find_package(hip)
    find_package(hipCUB)
    if(hip_FOUND AND TARGET hip::hipcub)
        set(HAS_HIP_CUB 1)
    endif()
endif()

foreach(source src/scan.cpp src/scan_improved.cpp)
    get_filename_component(name ${source} NAME_WE)
    alpakatune_add_example(${name} ${source})
    target_include_directories(alpakaTune_${name} PRIVATE src)
    if(HAS_CUDA_CUB)
        target_link_libraries(alpakaTune_${name} PRIVATE CUDA::cudart_static)
        target_compile_definitions(alpakaTune_${name} PRIVATE ALPAKA_HAS_CUB=1)
    endif()
    if(HAS_HIP_CUB)
        target_link_libraries(alpakaTune_${name} PRIVATE hip::hipcub)
        target_compile_definitions(alpakaTune_${name} PRIVATE ALPAKA_HAS_HIPCUB=1)
    endif()
endforeach()
