add_executable(alpakaTune_session_tests tuning_session.cpp)
target_link_libraries(alpakaTune_session_tests PRIVATE alpakaTune::alpakaTune)
alpaka_finalize(alpakaTune_session_tests)
add_test(NAME alpakaTune_session_tests COMMAND alpakaTune_session_tests)

add_executable(alpakaTune_candidate_queue_tests candidate_queue.cpp)
target_link_libraries(alpakaTune_candidate_queue_tests PRIVATE alpakaTune::alpakaTune)
alpaka_finalize(alpakaTune_candidate_queue_tests)
add_test(NAME alpakaTune_candidate_queue_tests COMMAND alpakaTune_candidate_queue_tests)

add_executable(alpakaTune_strategy_tests strategy.cpp)
target_link_libraries(alpakaTune_strategy_tests PRIVATE alpakaTune::alpakaTune)
alpaka_finalize(alpakaTune_strategy_tests)
add_test(NAME alpakaTune_strategy_tests COMMAND alpakaTune_strategy_tests)

add_executable(alpakaTune_runtime_history_tests runtime_history.cpp)
target_link_libraries(alpakaTune_runtime_history_tests PRIVATE alpakaTune::alpakaTune)
alpaka_finalize(alpakaTune_runtime_history_tests)
add_test(NAME alpakaTune_runtime_history_tests COMMAND alpakaTune_runtime_history_tests)
